In [1]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;

In [2]:
df = pd.read_csv("housing.csv");

In [3]:
df['income_cat'] = pd.cut(df['median_income'], bins = [0, 1.5, 3.0, 4.5, 6.0, np.inf], labels = [1, 2, 3, 4, 5]);

In [4]:
from sklearn.model_selection import StratifiedShuffleSplit;
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42);
for train_index, test_index in split.split(df, df['income_cat']):
    strat_train_set = df.loc[train_index];
    strat_test_set = df.loc[test_index];

In [5]:
# Remove income_cat column:-
for sett in (strat_train_set, strat_test_set):
    sett.drop("income_cat", axis = 1, inplace = True);

In [6]:
df = strat_train_set.copy();

In [7]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736,72100,INLAND
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373,279600,NEAR OCEAN
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750,82700,INLAND
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264,112500,NEAR OCEAN
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964,238300,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900,268500,<1H OCEAN
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139,90400,INLAND
19263,-122.72,38.44,48,707,166.0,458,172,3.1797,140400,<1H OCEAN
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964,258100,<1H OCEAN
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319,62700,INLAND

In [8]:
housing = strat_train_set.drop("median_house_value", axis = 1);
housing_labels = strat_train_set["median_house_value"].copy();

In [9]:
housing = housing.drop("ocean_proximity", axis = 1);

In [10]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964
...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139
19263,-122.72,38.44,48,707,166.0,458,172,3.1797
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319

In [11]:
from sklearn.pipeline import Pipeline;
from sklearn.impute import SimpleImputer;
from sklearn.preprocessing import StandardScaler;

In [12]:
mypipeline = Pipeline([
    ("impute", SimpleImputer(strategy = "median")),
     ("standardize", StandardScaler()),
]);

In [13]:
mypipeline.fit_transform(housing)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.73260236,
         0.55628602, -0.8936472 ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.53361152,
         0.72131799,  1.292168  ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.67467519,
        -0.52440722, -0.52543365],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.86201341,
        -0.86511838, -0.36547546],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.18974707,
         0.01061579,  0.16826095],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.71232211,
        -0.79857323, -0.390569  ]], shape=(16512, 8))