In [1]:
import pandas as pd;

In [2]:
df = pd.read_csv("data.csv");

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df = df[df['IMDb'] > 8.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.to_csv("data_update.csv")

In [7]:
df.to_csv("data_updated.csv", index = False)

In [8]:
df = pd.read_json("data1.json")

In [9]:
df

   id   name                                  address
0   1  Alice   {'city': 'Delhi', 'zipcode': '110001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '400001'}

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       2 non-null      int64
 1   name     2 non-null      object
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [11]:
data = [
  {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
  {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
];

In [12]:
df = pd.json_normalize(data);

In [13]:
df

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 196.0+ bytes